"""
Django settings for COMP3297 project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$xfh%%8=3d!gf3f7x!cs(+!9rn7r!2u2umt#7_&20%yk2k4yyw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unihaven.apps.UnihavenConfig',
    # 'django.contrib.admin', # Commented out for demo API
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'COMP3297.urls'

import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR), 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'COMP3297.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # Keep Browsable API for easy testing
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Email settings (for development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'unihaven@example.com'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'reservation_activities.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
# Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Unihaven API',
    'DESCRIPTION': '''
API for Unihaven project - a platform for HKU student accommodation management.

## Role-Based Access Control

This API implements role-based access control through query parameters. For most endpoints, you must include a `role` query parameter with one of the following formats:

- `cedars_specialist`: For CEDARS staff members (ID optional for some general actions like listing all owners/members/specialists).
- `cedars_specialist:<id>`: For CEDARS staff members performing actions requiring their specific ID (e.g., retrieving managed accommodations).
- `hku_member:<uid>`: For HKU students and staff (UID is generally required).

### Required Role Parameter

Most endpoints require the `role` parameter to be included in the request. For example:
```
GET /accommodations/?role=hku_member:u1234567
POST /property-owners/?role=cedars_specialist
GET /reservations/?role=cedars_specialist:1 # Requires ID for specialist
GET /hku-members/u1234567/reservations/?role=hku_member:u1234567 # Requires matching ID
```

### Resource-Oriented Design & Actions

The API generally follows a resource-oriented design. Specific actions often use dedicated sub-paths:
- Creating a reservation: Use `POST /reservations/create/`
- Canceling a reservation: Use `POST /reservations/{id}/cancel/`
- Rating an accommodation: Use `POST /ratings/create/`
- Listing managed accommodations: Use `GET /cedars-specialists/{id}/managed_accommodations/`

**Note on Authentication/Permissions:** Some actions (notably Reservation creation/cancellation/listing and Rating creation/updating) use manual role checks within the view code and bypass standard DRF authentication/permission classes. This was done to resolve CSRF issues with non-browser clients while keeping CSRF protection enabled globally. The auto-generated schema may not fully reflect this bypass for those specific actions.

### Permission Rules Summary:

1.  **Property Owners (`/property-owners/`)**: Only CEDARS Specialists (ID optional) can perform List, Create, Retrieve, Update, Delete.
2.  **Accommodations (`/accommodations/`)**:
    - List/Search: Any HKU Member (`hku_member:uid`) or CEDARS Specialist (`cedars_specialist[:id]`).
    - Retrieve: Any HKU Member (`hku_member:uid`) or CEDARS Specialist (`cedars_specialist[:id]`).
    - Create/Update/Delete: Only CEDARS Specialists (`cedars_specialist[:id]`).
    - `/search/` endpoint available for filtering.
    - *Note: `/accommodations/{id}/reservations/` endpoint is currently not implemented/exposed.*
3.  **HKU Members (`/hku-members/`)**:
    - List/Create/Delete: Only CEDARS Specialists (`cedars_specialist[:id]`).
    - Retrieve/Update: Any CEDARS Specialist (`cedars_specialist[:id]`) OR the specific HKU Member themselves (`hku_member:<uid>`).
    - List Reservations (`/hku-members/{uid}/reservations/`): Any CEDARS Specialist (`cedars_specialist[:id]`) OR the specific HKU Member themselves (`hku_member:<uid>`).
4.  **CEDARS Specialists (`/cedars-specialists/`)**: Only CEDARS Specialists (`cedars_specialist[:id]`) can perform List, Create, Retrieve, Update, Delete (including managing other specialists).
    - List Managed Accommodations (`/cedars-specialists/{id}/managed_accommodations/`): Only the specific CEDARS Specialist (`cedars_specialist:<id>`).
5.  **Reservations (`/reservations/`, `/reservations/create/`, `/reservations/{id}/cancel/`)**:
    - List (`GET /reservations/`): Only CEDARS Specialists (`cedars_specialist[:id]`) - manual check implemented. HKU Members use `/hku-members/{uid}/reservations/`.
    - Create (`POST /reservations/create/`): Any HKU Member (`hku_member:uid`, for self) OR any CEDARS Specialist (`cedars_specialist[:id]`, requires `member_id` in request body) - manual check implemented.
    - Retrieve (`GET /reservations/{id}/`): Any CEDARS Specialist (`cedars_specialist[:id]`) OR the HKU Member (`hku_member:uid`) who owns the reservation.
    - Cancel (`POST /reservations/{id}/cancel/`): Any CEDARS Specialist (`cedars_specialist[:id]`) OR the HKU Member (`hku_member:uid`) who owns the reservation - manual check implemented.
    - Update (`PUT /reservations/{id}/`): Only CEDARS Specialists (`cedars_specialist[:id]`) - manual check implemented.
    - Partial Update (`PATCH /reservations/{id}/`): **Disabled.** Use PUT for full updates.
    - Delete (`DELETE /reservations/{id}/`): Only CEDARS Specialists (`cedars_specialist[:id]`).
6.  **Ratings (`/ratings/`, `/ratings/create/`)**:
    - List (`GET /ratings/`): Any CEDARS Specialist (`cedars_specialist[:id]`) (can list all); HKU Members (`hku_member:uid`) can list their own (filtered).
    - Create (`POST /ratings/create/`): Only HKU Members (`hku_member:uid`) for their own completed reservations - manual check implemented.
    - Retrieve (`GET /ratings/{id}/`): Any CEDARS Specialist (`cedars_specialist[:id]`) OR the HKU Member (`hku_member:uid`) who owns the rating's reservation.
    - Update (`PUT /ratings/{id}/`): Only CEDARS Specialists (`cedars_specialist[:id]`) - manual check implemented.
    - Delete (`DELETE /ratings/{id}/`): Only CEDARS Specialists (`cedars_specialist[:id]`).

If you attempt to access an endpoint without the required role or permission, you should receive a 403 Forbidden or 400 Bad Request error with an appropriate error message.

## Features

- CEDARS Specialists can manage accommodations, property owners, and handle reservations
- HKU members can search accommodations, make reservations, and rate their stays
- Property owners are managed entities in the system, not users with direct API access
''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/v1',
    # Additional helpful settings
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_SPLIT_RESPONSE': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
    },
    'SWAGGER_UI_DIST': '//unpkg.com/swagger-ui-dist@5.9.0',
    'REDOC_DIST': '//cdn.jsdelivr.net/npm/redoc@2.0.0/bundles/redoc.standalone.js',
    'TAGS': [
        {'name': 'accommodations', 'description': 'Operations related to student accommodations'},
        {'name': 'cedars-specialists', 'description': 'Operations related to CEDARS specialists'},
        {'name': 'hku-members', 'description': 'Operations related to HKU members'},
        {'name': 'property-owners', 'description': 'Operations related to managing property owners'},
        {'name': 'ratings', 'description': 'Operations for managing ratings associated with accommodations'},
        {'name': 'reservations', 'description': 'Operations for managing reservations'},
    ],
    # Add explicit schema generation settings
    'QUERY_PARAM_REGEX': '.*',
    'SCHEMA_COERCE_PATH_PK_SUFFIX': True,
    'CAMELIZE_NAMES': False,
    'PREPROCESSING_HOOKS': [],
    'POSTPROCESSING_HOOKS': [],
    'ENUM_NAME_OVERRIDES': {},
}
