"""
Django settings for COMP3297 project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$xfh%%8=3d!gf3f7x!cs(+!9rn7r!2u2umt#7_&20%yk2k4yyw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unihaven.apps.UnihavenConfig',
    # 'django.contrib.admin', # Commented out for demo API
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'COMP3297.urls'

import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR), 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'COMP3297.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    # Temporarily disable default authentication for testing
    'DEFAULT_AUTHENTICATION_CLASSES': [], 
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # Keep Browsable API for easy testing
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Email settings (for development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'unihaven@example.com'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'reservation_activities.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'unihaven': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
# Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Unihaven API',
    'DESCRIPTION': '''
API for Unihaven project - a platform for university student accommodation management.

## Role-Based Access Control

This API implements role-based access control through query parameters. For most endpoints, you must include a `role` query parameter with one of the following formats:

- `uni_code:specialist:<id>`: For University Specialists performing actions requiring their specific ID (e.g., retrieving managed accommodations). The `id` is sometimes optional for general list actions.
- `uni_code:member:<uid>`: For University Members (students/staff, identified by UID).

Where `uni_code` is the code for the university (e.g., 'hku', 'cu', 'hkust').

### Required Role Parameter

Most endpoints require the `role` parameter to be included in the request. For example:
```
GET /accommodations/?role=hku:member:u1234567
POST /property-owners/?role=hku:specialist:1
GET /reservations/?role=cu:specialist:1 # Requires ID for specialist
GET /members/hku:u1234567/reservations/?role=hku:member:u1234567 # Requires matching ID
```

### Resource-Oriented Design & Actions

The API generally follows a resource-oriented design. Specific actions often use dedicated sub-paths:
- Creating a reservation: Use `POST /reservations/` (logic handled in view)
- Canceling a reservation: Use `POST /reservations/{id}/cancel/`
- Confirming a reservation: Use `POST /reservations/{id}/confirm/`
- Rating an accommodation: Use `POST /ratings/` (logic handled in view)

**Note on Authentication/Permissions:** Role checks are implemented via custom permission classes and logic within the viewsets. Standard DRF authentication (SessionAuthentication, BasicAuthentication) is assumed.

### Permission Rules Summary (Simplified):

1.  **Property Owners (`/property-owners/`)**: Only Specialists (`uni_code:specialist[:id]`) can perform List, Create, Retrieve, Update, Delete.
2.  **Accommodations (`/accommodations/`)**:
    - List/Retrieve: Any Member (`uni_code:member:uid`) or Specialist (`uni_code:specialist[:id]`). View filters by university.
    - Create/Update/Delete: Only Specialists (`uni_code:specialist[:id]`) whose university is linked to the accommodation.
3.  **Members (`/members/`)**:
    - List/Create/Delete: Only Specialists (`uni_code:specialist[:id]`) from the target university.
    - Retrieve/Update: Specialists (`uni_code:specialist[:id]`) from the same university OR the specific Member themselves (`uni_code:member:<uid>`).
    - List Reservations (`/members/{uid}/reservations/`): Specialists (`uni_code:specialist[:id]`) from the same university OR the specific Member themselves (`uni_code:member:<uid>`).
4.  **Specialists (`/specialists/`)**: 
    - List/Retrieve: Only Specialists (`uni_code:specialist[:id]`) from the same university.
    - Create/Update/Delete: Restricted (likely Admin/Superuser only).
5.  **Reservations (`/reservations/`)**:
    - List (`GET /reservations/`): Members (`uni_code:member:uid`) see their own; Specialists (`uni_code:specialist[:id]`) see their university's.
    - Create (`POST /reservations/`): Members (`uni_code:member:uid`) for self; Specialists (`uni_code:specialist[:id]`) for members in their university (requires `member_uid` in body).
    - Retrieve/Update (`GET/PUT/PATCH /reservations/{id}/`): Member owner (`uni_code:member:uid`) or Specialist (`uni_code:specialist[:id]`) from the reservation's university.
    - Cancel (`POST /reservations/{id}/cancel/`): Member owner or Specialist from the reservation's university.
    - Confirm (`POST /reservations/{id}/confirm/`): Specialist from the reservation's university.
    - Delete (`DELETE /reservations/{id}/`): Specialist from the reservation's university.
6.  **Ratings (`/ratings/`)**:
    - List (`GET /ratings/`): Members (`uni_code:member:uid`) see their own; Specialists (`uni_code:specialist[:id]`) see their university's.
    - Create (`POST /ratings/`): Only Members (`uni_code:member:uid`) for their own completed reservations.
    - Retrieve (`GET /ratings/{id}/`): Member owner or Specialist from the rating's university.
    - Delete (`DELETE /ratings/{id}/`): Specialist from the rating's university.
    - Update: Restricted.

If you attempt to access an endpoint without the required role or permission, you should receive a 403 Forbidden or 400 Bad Request error with an appropriate error message.

## Features

- University Specialists can manage accommodations, property owners, and handle reservations for their university.
- University Members can search accommodations, make reservations, and rate their stays.
- Property owners are managed entities in the system, not users with direct API access.
''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/v1',
    # Additional helpful settings
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_SPLIT_RESPONSE': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
    },
    'SWAGGER_UI_DIST': '//unpkg.com/swagger-ui-dist@5.9.0',
    'REDOC_DIST': '//cdn.jsdelivr.net/npm/redoc@2.0.0/bundles/redoc.standalone.js',
    # Update Tags to reflect unified models
    'TAGS': [
        {'name': 'accommodations', 'description': 'Operations related to student accommodations'},
        {'name': 'specialists', 'description': 'Operations related to University Specialists'},
        {'name': 'members', 'description': 'Operations related to University Members'},
        {'name': 'property-owners', 'description': 'Operations related to managing property owners'},
        {'name': 'ratings', 'description': 'Operations for managing ratings associated with accommodations'},
        {'name': 'reservations', 'description': 'Operations for managing reservations'},
    ],
    # Add explicit schema generation settings
    'QUERY_PARAM_REGEX': '.*',
    'SCHEMA_COERCE_PATH_PK_SUFFIX': True,
    'CAMELIZE_NAMES': False,
    'PREPROCESSING_HOOKS': [],
    'POSTPROCESSING_HOOKS': [],
    'ENUM_NAME_OVERRIDES': {},
}
