# Generated by Django 5.1.7 on 2025-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unihaven', '0002_alter_accommodation_geo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
