# Generated by Django 5.1.7 on 2025-04-12 06:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unihaven', '0003_alter_accommodation_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyowner',
            old_name='contact_info',
            new_name='phone_no',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='rating',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accommodations', to='unihaven.cedarsspecialist'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cancelled_by', models.CharField(blank=True, max_length=50, null=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='unihaven.accommodation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='unihaven.hkumember')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('date_rated', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='unihaven.reservation')),
            ],
        ),
    ]
