# Generated by Django 5.2 on 2025-04-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unihaven", "0005_cedarsspecialist_user_hkumember_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
