# Generated by Django 5.1.7 on 2025-04-26 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unihaven', '0007_university_remove_accommodation_specialist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Main Campus, Sassoon Road Campus', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['university__code', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='cedarsspecialist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cuhkmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cuhkspecialist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hkumember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hkustmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hkustspecialist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='available_university',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='available_at_universities',
            field=models.ManyToManyField(related_name='available_accommodations', to='unihaven.university'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='flat_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='floor_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='geo_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='unihaven.university'),
        ),
        migrations.AddConstraint(
            model_name='accommodation',
            constraint=models.UniqueConstraint(fields=('room_number', 'flat_number', 'floor_number', 'geo_address'), name='unique_physical_address'),
        ),
        migrations.AddField(
            model_name='member',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='unihaven.university'),
        ),
        # Restore FK constraint
        migrations.AlterField(
            model_name='reservation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='unihaven.member'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='unihaven.university'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='universitylocation',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='unihaven.university'),
        ),
        migrations.DeleteModel(
            name='CEDARSSpecialist',
        ),
        migrations.DeleteModel(
            name='CUHKMember',
        ),
        migrations.DeleteModel(
            name='CUHKSpecialist',
        ),
        migrations.DeleteModel(
            name='HKUSTMember',
        ),
        migrations.DeleteModel(
            name='HKUSTSpecialist',
        ),
        migrations.DeleteModel(
            name='HKUMember',
        ),
        migrations.AlterUniqueTogether(
            name='universitylocation',
            unique_together={('university', 'name')},
        ),
    ]
