# Generated by Django 5.2 on 2025-04-28 17:23

from django.db import migrations


def add_university_locations(apps, schema_editor):
    University = apps.get_model('unihaven', 'University')
    UniversityLocation = apps.get_model('unihaven', 'UniversityLocation')
    hku = University.objects.get(code='HKU')
    cu = University.objects.get(code='CU')
    hkust = University.objects.get(code='HKUST')

    UniversityLocation.objects.create(university=hku, name='Main Campus', latitude=22.28405, longitude=114.13784)
    UniversityLocation.objects.create(university=hku, name='Sassoon Road Campus', latitude=22.2675, longitude=114.12881)
    UniversityLocation.objects.create(university=hku, name='Swire Institute of Marine Science', latitude=22.20805, longitude=114.26021)
    UniversityLocation.objects.create(university=hku, name='Kadoorie Centre', latitude=22.43022, longitude=114.11429)
    UniversityLocation.objects.create(university=hku, name='Faculty of Dentistry', latitude=22.28649, longitude=114.14426)
    UniversityLocation.objects.create(university=cu, name='Main Campus', latitude=22.41907, longitude=114.20693)
    UniversityLocation.objects.create(university=hkust, name='Main Campus', latitude=22.33584, longitude=114.26355)

class Migration(migrations.Migration):
    dependencies = [('unihaven', '0009_member_user')]
    operations = [migrations.RunPython(add_university_locations)]