# Generated by Django 5.1.7 on 2025-04-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unihaven', '0009_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
