# Generated by Django 5.1.7 on 2025-04-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unihaven', '0011_alter_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='building_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
