# Generated by Django 5.1.7 on 2025-05-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unihaven', '0012_accommodation_building_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='contact',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
